doc: Use Maven Wrapper in README
vaadin/base-starter-flow-quarkus pull request #42
Opened 2022-05-28 21:09 UTC by felix-seifert

## Description

The simple usage of Maven Wrapper ensures consistency throughout the branches. Furthermore, devs can use Maven Wrapper without installing Maven on their machine.

## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] Documentation

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-05-28 21:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/base-starter-flow-quarkus?pullRequest=42) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/base-starter-flow-quarkus?pullRequest=42) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/base-starter-flow-quarkus?pullRequest=42) it.</sub>

2022-05-30 11:41 UTC, mshabarov approved these changes

2022-05-30 11:45 UTC, mshabarov requested changes
Should be `vaadin:v23` branch, not `vaadin:native-image`.

2022-05-30 11:54 UTC, felix-seifert commented
> Should be `vaadin:v23` branch, not `vaadin:native-image`.

I understand the concern. This change is however relevant to `vaadin:native-image`; the change with the usage of Maven Wrapper makes it more similar to `vaadin:v23`.

2022-05-30 14:00 UTC, mshabarov approved these changes

2022-05-30 14:00 UTC, merged